export default {
  name: '@nipakke/vike-plugins',
  // At runtime, the runner module dynamically imports the virtual module
  // `virtual:vike-plugins` (generated by the Vite plugin) and calls
  // runPlugins() with all auto-discovered plugin files from the user's
  // project.
  onCreatePageContext: 'import:@nipakke/vike-plugins/runner:onCreatePageContext',
}
