import type { Plugin } from 'vite'
import { resolve } from 'node:path'
import { readdirSync } from 'node:fs'

async function generateTypes() {
  const pluginsDir = resolve(process.cwd(), 'plugins')
  const outFile = resolve(process.cwd(), '.vike/plugins.d.ts')

  const files = readdirSync(pluginsDir)
  const plugins = files.filter(f => f.match(/\.(ts|js|mts)$/))

  const imports = plugins
    .map(f => `  InjectionType<typeof import('../plugins/${f}')>`)
    .join(' &\n')

  const content = `// generated by vike-plugins — do not edit
import type { Plugin } from 'your-lib'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? \`$\${K}\` : never]: T[K] }
type InjectionType<A> = A extends { default: Plugin<infer T> } ? Decorate<T> : unknown

type VikeAppInjections =
${imports}

declare module 'your-lib' {
  interface VikeAppContext extends VikeAppInjections {}
}

export {}
`

  console.log(content)

  /*   await mkdir(resolve(process.cwd(), '.vike'), { recursive: true })
    await writeFile(outFile, content, 'utf-8') */
}


export default (): Plugin => {
  return {
    name: "vike-plugins",
    async buildStart() {
      console.log("GENERATE TYPES")
      await generateTypes()
    },

    configureServer(server) {
      const pluginsDir = resolve(process.cwd(), 'plugins')

      /* server.watcher.add(pluginsDir)
      server.watcher.on('add', (path) => {
        if (path.startsWith(pluginsDir)) void generateTypes()
      })
      server.watcher.on('unlink', (path) => {
        if (path.startsWith(pluginsDir)) void generateTypes()
      }) */

    }


  }
}