import type { PageContext } from 'vike/types'

/**
 * Static onCreatePageContext hook that the user imports and sets
 * in their +config.ts. At runtime (inside Vite's SSR module system),
 * it dynamically imports the virtual module `virtual:vike-plugins`
 * (generated by the Vite plugin) and executes all discovered plugins
 * via runPlugins().
 */

export async function onCreatePageContext(pageContext: PageContext): Promise<void> {
  // Dynamic imports — only resolved at runtime inside Vite's SSR context
  const [{ runPlugins }, mod] = await Promise.all([
    import('@nipakke/vike-plugins/vike'),
    import('virtual:vike-plugins'),
  ])

  const plugins = mod.rawPlugins ?? []
  if (plugins.length > 0) {
    await runPlugins(plugins, pageContext)
  }
}
