import { describe, it, expect } from 'vitest'
import { generateVirtualModule } from '../../src/vite/virtual-module.js'
import type { PluginFileInfo } from '../../src/vite/types.js'

describe('generateVirtualModule', () => {
  const pluginsDir = '/project/plugins'

  it('generates a record keyed by normalized plugin name', () => {
    const files: PluginFileInfo[] = [
      { filename: 'auth.ts', mode: 'universal', baseName: 'auth' },
    ]

    const output = generateVirtualModule(files, pluginsDir)

    expect(output).toMatchInlineSnapshot(`
      "// ============================================================
      // virtual:vike-plugins
      // ============================================================
      //
      // Auto-generated by vike-plugins.
      // Plugins run only on the server (onCreatePageContext hook).
      //
      // ============================================================

      // auth.ts
      let plugin_0
      try {
        const mod_0 = await import('/project/plugins/auth.ts')
        plugin_0 = mod_0.default
        if (!plugin_0 || typeof plugin_0 !== 'object' || typeof plugin_0.setup !== 'function') {
          console.warn(\`[vike-plugins] File "auth.ts" does not export a valid VikePlugin (expected default export from definePlugin()). Skipping.\`)
          plugin_0 = null
        }
      } catch (err) {
        console.warn(\`[vike-plugins] Failed to load plugin "auth.ts":\`, err instanceof Error ? err.message : err)
        plugin_0 = null
      }

      export const rawPlugins = {
        auth: plugin_0
      }
      "
    `)
  })

  it('includes multiple plugins in the record', () => {
    const files: PluginFileInfo[] = [
      { filename: 'auth.ts', mode: 'universal', baseName: 'auth' },
      { filename: 'db.ts', mode: 'universal', baseName: 'db' },
    ]

    const output = generateVirtualModule(files, pluginsDir)

    expect(output).toContain('auth: plugin_0')
    expect(output).toContain('db: plugin_1')
  })

  it('quotes keys that are not valid JS identifiers', () => {
    const files: PluginFileInfo[] = [
      { filename: 'db-v2.ts', mode: 'universal', baseName: 'db-v2' },
    ]

    const output = generateVirtualModule(files, pluginsDir)

    expect(output).toContain("'db-v2': plugin_0")
  })

  it('returns empty record for empty input', () => {
    const files: PluginFileInfo[] = []

    const output = generateVirtualModule(files, pluginsDir)

    expect(output).toMatchInlineSnapshot(`
      "// ============================================================
      // virtual:vike-plugins
      // ============================================================
      //
      // Auto-generated by vike-plugins.
      // Plugins run only on the server (onCreatePageContext hook).
      //
      // ============================================================

      export const rawPlugins = {}
      "
    `)
  })

  it('throws Error when duplicate normalized names are detected', () => {
    const files: PluginFileInfo[] = [
      { filename: 'auth-v1.ts', mode: 'universal', baseName: 'auth' },
      { filename: 'auth-v2.ts', mode: 'universal', baseName: 'auth' },
    ]

    expect(() => generateVirtualModule(files, pluginsDir)).toThrow(
      'Duplicate plugin names detected after normalization:',
    )
    expect(() => generateVirtualModule(files, pluginsDir)).toThrow('"auth"')
  })

  it('does NOT throw when plugins have different baseNames', () => {
    const files: PluginFileInfo[] = [
      { filename: 'auth.ts', mode: 'universal', baseName: 'auth' },
      { filename: 'db.ts', mode: 'universal', baseName: 'db' },
    ]

    expect(() => generateVirtualModule(files, pluginsDir)).not.toThrow()
  })
})
