import { writeFileSync, mkdirSync } from 'node:fs'
import { resolve } from 'node:path'
import type { PluginFileInfo } from './types'

const TYPES_FILENAME = 'vike-plugins.d.ts'

function propertyKey(name: string): string {
  if (/^[a-zA-Z_$][\w$]*$/.test(name)) return name
  return `'${name}'`
}

function buildPluginEntries(
  pluginFiles: PluginFileInfo[],
  pluginsDir: string,
  indent: string,
): string {
  if (pluginFiles.length === 0) {
    return `${indent}// No plugins discovered`
  }
  return pluginFiles
    .map((file) => {
      const absPath = resolve(pluginsDir, file.filename).replace(/\\/g, '/')
      const key = propertyKey(file.baseName)
      return `${indent}// @plugin ${file.filename}
${indent}${key}: PluginProvide<typeof import('${absPath}').default>`
    })
    .join('\n')
}

export function generateTypeDeclaration(
  pluginFiles: PluginFileInfo[],
  pluginsDir: string,
): string {
  const $pluginsEntries = buildPluginEntries(pluginFiles, pluginsDir, '        ')
  const providesEntries = buildPluginEntries(pluginFiles, pluginsDir, '  ')

  return `\
// Auto-generated by vike-plugins — do not edit
// Augments Vike PageContext with plugin provide types

import type { PluginProvide } from '@nipakke/vike-plugins/vike'
export {}

declare global {
  namespace Vike {
    interface PageContext {
      $plugins: {
${$pluginsEntries}
      }
    }
  }
}

export type PluginProvides = {
${providesEntries}
}

export type PluginProvideLookup<K extends keyof PluginProvides> = PluginProvides[K]
`
}

export function writeTypeFile(
  root: string,
  pluginFiles: PluginFileInfo[],
  pluginsDir: string,
  outDir: string,
): void {
  const fullDir = resolve(root, outDir)
  mkdirSync(fullDir, { recursive: true })
  const content = generateTypeDeclaration(pluginFiles, pluginsDir)
  writeFileSync(resolve(fullDir, TYPES_FILENAME), content, 'utf-8')
}
