import type { Plugin, ViteDevServer } from 'vite'
import { readdirSync, existsSync, writeFileSync, mkdirSync } from 'node:fs'
import { resolve, extname, basename, dirname, join } from 'node:path'

export interface VikePluginsOptions {
  /** Directory to scan for plugin files. Defaults to 'plugins/'. */
  dir?: string
}

const VIRTUAL_ID = 'virtual:vike-plugins'
const RESOLVED_VIRTUAL_ID = '\0' + VIRTUAL_ID

/** Vike convention: generated files live in .vike/ at the project root */
const VIKE_DIR = '.vike'
const TYPES_OUTPUT = join(VIKE_DIR, 'vike-plugins.d.ts')

/**
 * File mode: which environment(s) the plugin loads in.
 */
export type PluginFileMode = 'server' | 'client' | 'universal'

export interface PluginFileInfo {
  filename: string
  mode: PluginFileMode
  baseName: string
}

/**
 * Scan a directory for TypeScript/JavaScript plugin files.
 * Detects .server.ts / .client.ts suffixes to determine loading mode.
 * Files without a mode suffix are treated as universal.
 */
export function scanDirectory(dir: string): PluginFileInfo[] {
  if (!existsSync(dir)) return []

  try {
    const files = readdirSync(dir)
    const pluginFiles: PluginFileInfo[] = []

    for (const file of files) {
      if (file.startsWith('.') || file.startsWith('__')) continue
      if (!/\.(ts|js|mts|mjs)$/.test(file)) continue

      const ext = extname(file)
      const base = basename(file, ext)

      let mode: PluginFileMode = 'universal'
      let baseName = base

      if (base.endsWith('.server')) {
        mode = 'server'
        baseName = base.slice(0, -7)
      } else if (base.endsWith('.client')) {
        mode = 'client'
        baseName = base.slice(0, -7)
      }

      pluginFiles.push({ filename: file, mode, baseName })
    }

    return pluginFiles.sort((a, b) => a.filename.localeCompare(b.filename))
  } catch {
    return []
  }
}

/**
 * Generate the virtual module source.
 *
 * Vite's `load` hook receives `{ ssr: boolean }` — we use this to
 * generate a DIFFERENT module for server vs client builds:
 *
 *   - SSR build:   only server + universal plugins
 *   - Client build: only client + universal plugins
 *
 * The opposite-environment plugins are never imported — they're
 * completely absent from the module source, so they can't end up in
 * the wrong bundle. No tree-shaking reliance.
 */
export function generateVirtualModule(
  pluginFiles: PluginFileInfo[],
  pluginsDir: string,
  isSSR: boolean,
): string {
  const active = pluginFiles.filter((f) => {
    if (f.mode === 'universal') return true
    if (f.mode === 'server') return isSSR
    if (f.mode === 'client') return !isSSR
    return false
  })

  const envLabel = isSSR ? 'SSR' : 'client'

  const lines: string[] = [
    '// ============================================================',
    `// virtual:vike-plugins — ${envLabel} build`,
    '// ============================================================',
    '//',
    `// Only plugins for the ${envLabel} environment are listed below.`,
    '// Opposite-environment plugins are completely absent.',
    `//   *.server.ts  → ${isSSR ? 'INCLUDED' : 'EXCLUDED'}`,
    `//   *.client.ts  → ${!isSSR ? 'INCLUDED' : 'EXCLUDED'}`,
    '//   *.ts         → always included',
    '//',
    '// ============================================================',
    '',
  ]

  if (active.length === 0) {
    lines.push('export const rawPlugins = []')
    lines.push('')
    return lines.join('\n')
  }

  const varNames: string[] = []

  for (let i = 0; i < active.length; i++) {
    const file = active[i]
    const absPath = resolve(pluginsDir, file.filename)
    const varName = `plugin_${i}`

    lines.push(`// ${file.filename} (${file.mode})`)
    lines.push(`const ${varName} = (await import('${absPath}')).default`)
    lines.push(
      `if (!${varName}.name || ${varName}.name === 'unnamed') ${varName}.name = '${file.baseName}'`,
    )
    lines.push('')
    varNames.push(varName)
  }

  lines.push(`export const rawPlugins = [${varNames.join(', ')}]`)
  lines.push('')

  return lines.join('\n')
}

/**
 * Generate and write the type declaration file to disk.
 *
 * Written to `.vike/vike-plugins.d.ts` so TypeScript picks it up
 * automatically (the user's tsconfig already includes `.vike/*.d.ts`).
 */
export function generateTypeDeclaration(
  pluginFiles: PluginFileInfo[],
  pluginsDir: string,
): string {
  const lines: string[] = [
    '// Auto-generated by vike-plugins — do not edit',
    '// Augments Vike PageContext with plugin provide types',
    '',
    "import type { PluginProvide } from '@nipakke/vike-plugins/vike'",
    'export {}',
    '',
    'declare global {',
    '  namespace Vike {',
    '    interface PageContext {',
    '      $plugins: {',
  ]

  if (pluginFiles.length === 0) {
    lines.push('        // No plugins discovered')
  } else {
    for (const file of pluginFiles) {
      const absPath = resolve(pluginsDir, file.filename).replace(/\\/g, '/')
      const key = propertyKey(file.baseName)
      lines.push(`        // @plugin ${file.filename}`)
      lines.push(
        `        ${key}: PluginProvide<typeof import('${absPath}').default>`,
      )
    }
  }

  lines.push('      }')
  lines.push('    }')
  lines.push('  }')
  lines.push('}')
  lines.push('')
  lines.push('export type PluginProvides = {')

  if (pluginFiles.length === 0) {
    lines.push('  // No plugins discovered')
  } else {
    for (const file of pluginFiles) {
      const absPath = resolve(pluginsDir, file.filename).replace(/\\/g, '/')
      const key = propertyKey(file.baseName)
      lines.push(`  // @plugin ${file.filename}`)
      lines.push(
        `  ${key}: PluginProvide<typeof import('${absPath}').default>`,
      )
    }
  }

  lines.push('}')
  lines.push('')
  lines.push('export type PluginProvideLookup<K extends keyof PluginProvides> = PluginProvides[K]')
  lines.push('')

  return lines.join('\n')
}

/** Write the type declaration file to disk inside the project root. */
function writeTypeFile(root: string, pluginFiles: PluginFileInfo[], pluginsDir: string): void {
  const outDir = resolve(root, VIKE_DIR)
  mkdirSync(outDir, { recursive: true })
  const content = generateTypeDeclaration(pluginFiles, pluginsDir)
  writeFileSync(resolve(outDir, 'vike-plugins.d.ts'), content, 'utf-8')
}

/** Quote property keys that aren't valid JS identifiers. */
function propertyKey(name: string): string {
  if (/^[a-zA-Z_$][\w$]*$/.test(name)) return name
  return `'${name}'`
}

/**
 * Vite plugin that auto-discovers VikePlugin files.
 *
 * Generates:
 * 1. `virtual:vike-plugins` — the plugin registry, filtered per build
 *    target via Vite's load() hook `ssr` option.
 * 2. `.vike/vike-plugins.d.ts` — type declarations written to disk
 *    so TypeScript picks them up automatically.
 */
export function vikePlugins(opts?: VikePluginsOptions): Plugin {
  const dir = opts?.dir ?? 'plugins/'
  let resolvedPluginsDir = ''
  let projectRoot = ''

  function getPluginsDir(): string {
    if (!resolvedPluginsDir) {
      resolvedPluginsDir = resolve(projectRoot || process.cwd(), dir)
    }
    return resolvedPluginsDir
  }

  function regenerateTypes(): void {
    if (!projectRoot) return
    const pd = getPluginsDir()
    const files = scanDirectory(pd)
    writeTypeFile(projectRoot, files, pd)
  }

  return {
    name: 'vike-plugins',
    enforce: 'pre',

    configResolved(config) {
      projectRoot = config.root
      // Generate types immediately once the project root is known
      regenerateTypes()
    },

    resolveId(id: string) {
      if (id === VIRTUAL_ID) return RESOLVED_VIRTUAL_ID
      return null
    },

    load(id: string, options?: { ssr?: boolean }) {
      if (id === RESOLVED_VIRTUAL_ID) {
        const pd = getPluginsDir()
        const files = scanDirectory(pd)
        return generateVirtualModule(files, pd, options?.ssr ?? false)
      }
      return null
    },

    configureServer(server: ViteDevServer) {
      projectRoot = server.config.root
      const pd = getPluginsDir()

      if (!existsSync(pd)) return

      server.watcher.add(pd)

      const isPluginFile = (path: string): boolean =>
        path.startsWith(pd) && /\.(ts|js|mts|mjs)$/.test(path)

      const handleChange = (path: string): void => {
        if (!isPluginFile(path)) return

        // Invalidate virtual module in both SSR and client graphs
        const mod = server.moduleGraph.getModuleById(RESOLVED_VIRTUAL_ID)
        if (mod) {
          server.moduleGraph.invalidateModule(mod)
        }
        // Also invalidate in the SSR module graph
        const ssrMod = server.moduleGraph.getModuleById(RESOLVED_VIRTUAL_ID)
        // Regenerate type file on disk
        regenerateTypes()

        server.ws.send({ type: 'full-reload' })
      }

      server.watcher.on('add', handleChange)
      server.watcher.on('unlink', handleChange)
      server.watcher.on('change', handleChange)
    },

    buildStart() {
      regenerateTypes()
    },
  }
}
