import type { Plugin, ViteDevServer } from 'vite'
import { readdirSync, existsSync } from 'node:fs'
import { resolve, extname, basename } from 'node:path'

export interface VikePluginsOptions {
  /** Directory to scan for plugin files. Defaults to 'plugins/'. */
  dir?: string
}

const VIRTUAL_ID = 'virtual:vike-plugins'
const RESOLVED_VIRTUAL_ID = '\0' + VIRTUAL_ID

/**
 * Scan a directory for TypeScript/JavaScript plugin files.
 * Skips hidden files (starting with . or __).
 */
function scanDirectory(dir: string): string[] {
  if (!existsSync(dir)) return []

  try {
    const files = readdirSync(dir)
    return files
      .filter((f) => {
        if (!/\.(ts|js|mts|mjs)$/.test(f)) return false
        if (f.startsWith('.') || f.startsWith('__')) return false
        return true
      })
      .sort()
  } catch {
    return []
  }
}

/**
 * Generate the virtual module source.
 * Imports all discovered plugin files and exports the rawPlugins array.
 * runPlugins() in the runner module handles sorting internally.
 */
function generateVirtualModule(pluginFiles: string[], pluginsDir: string): string {
  const makeVarName = (file: string, i: number): string => {
    const name = basename(file, extname(file))
    return `plugin_${name.replace(/[^a-zA-Z0-9]/g, '_')}_${i}`
  }

  const imports = pluginFiles.map((file, i) => {
    const absPath = resolve(pluginsDir, file)
    const varName = makeVarName(file, i)
    const inferredName = basename(file, extname(file))
    return [
      `import _mod_${i} from '${absPath}'`,
      `const ${varName} = _mod_${i}`,
      `if (!${varName}.name || ${varName}.name === 'unnamed') ${varName}.name = '${inferredName}'`,
    ].join('\n')
  })

  const pluginList = pluginFiles.map((f, i) => makeVarName(f, i)).join(', ')

  return [
    '// Auto-generated by vike-plugins — do not edit',
    '',
    imports.join('\n'),
    '',
    `export const rawPlugins = [${pluginList}]`,
    '',
  ].join('\n')
}

/**
 * Vite plugin that auto-discovers VikePlugin files and generates
 * a virtual module (`virtual:vike-plugins`) exporting the raw plugins.
 *
 * The runner module (`@nipakke/vike-plugins/runner`) dynamically
 * imports this virtual module at runtime and calls runPlugins().
 *
 * @example
 * ```typescript
 * // vite.config.ts
 * import { vikePlugins } from '@nipakke/vike-plugins/vite'
 * export default { plugins: [vikePlugins({ dir: './src/plugins' }), vike()] }
 * ```
 */
export function vikePlugins(opts?: VikePluginsOptions): Plugin {
  const dir = opts?.dir ?? 'plugins/'
  let resolvedPluginsDir = ''

  function getPluginsDir(): string {
    if (!resolvedPluginsDir) {
      resolvedPluginsDir = resolve(process.cwd(), dir)
    }
    return resolvedPluginsDir
  }

  return {
    name: 'vike-plugins',
    enforce: 'pre',

    resolveId(id: string) {
      if (id === VIRTUAL_ID) {
        return RESOLVED_VIRTUAL_ID
      }
      return null
    },

    load(id: string) {
      if (id === RESOLVED_VIRTUAL_ID) {
        const pluginsDir = getPluginsDir()
        const pluginFiles = scanDirectory(pluginsDir)
        return generateVirtualModule(pluginFiles, pluginsDir)
      }
      return null
    },

    configureServer(server: ViteDevServer) {
      const pluginsDir = getPluginsDir()

      if (!existsSync(pluginsDir)) return

      server.watcher.add(pluginsDir)

      const isPluginFile = (path: string): boolean =>
        path.startsWith(pluginsDir) && /\.(ts|js|mts|mjs)$/.test(path)

      const handleChange = (path: string): void => {
        if (!isPluginFile(path)) return

        const mod = server.moduleGraph.getModuleById(RESOLVED_VIRTUAL_ID)
        if (mod) {
          server.moduleGraph.invalidateModule(mod)
          server.ws.send({ type: 'full-reload' })
        }
      }

      server.watcher.on('add', handleChange)
      server.watcher.on('unlink', handleChange)
      server.watcher.on('change', handleChange)
    },
  }
}
