import { resolve } from 'node:path'
import type { PluginFileInfo } from './types'
import { normalizePluginName } from '../core/plugin-name.js'

function quoteKey(name: string): string {
  if (/^[a-zA-Z_$][\w$]*$/.test(name)) return name
  return `'${name}'`
}

export function detectDuplicateNames(
  files: PluginFileInfo[],
): Map<string, string[]> | null {
  const nameMap = new Map<string, string[]>()

  for (const file of files) {
    const name = normalizePluginName(file.baseName) || 'unnamed'
    const list = nameMap.get(name)
    if (list) {
      list.push(file.filename)
    } else {
      nameMap.set(name, [file.filename])
    }
  }

  const duplicates = new Map<string, string[]>()
  for (const [name, fileList] of nameMap) {
    if (fileList.length > 1) {
      duplicates.set(name, fileList)
    }
  }

  return duplicates.size > 0 ? duplicates : null
}

export function formatDuplicateError(duplicates: Map<string, string[]>): string {
  const lines: string[] = ['Duplicate plugin names detected after normalization:']

  for (const [name, fileList] of duplicates) {
    lines.push(`  - "${name}" from files: [${fileList.join(', ')}]`)
  }

  lines.push(
    'All plugin file names are normalized (lowercase, special chars replaced) for comparison.',
  )

  return lines.join('\n')
}

/**
 * Generate the virtual module source.
 *
 * Produces a module exporting `rawPlugins` — a record keyed by plugin name.
 * The name is derived from the filename (normalized), so `auth.ts` becomes
 * `{ auth: plugin_0 }` and `db-v2.ts` becomes `{ 'db-v2': plugin_0 }`.
 *
 * Plugins only run on the server (via onCreatePageContext), so no
 * SSR/client filtering is needed — all discovered plugins are included.
 */
export function generateVirtualModule(
  pluginFiles: PluginFileInfo[],
  pluginsDir: string,
): string {
  const duplicates = detectDuplicateNames(pluginFiles)
  if (duplicates) {
    throw new Error(formatDuplicateError(duplicates))
  }

  if (pluginFiles.length === 0) {
    return `\
// ============================================================
// virtual:vike-plugins
// ============================================================
//
// Auto-generated by vike-plugins.
// Plugins run only on the server (onCreatePageContext hook).
//
// ============================================================

export const rawPlugins = {}
`
  }

  const importBlocks: string[] = []
  const entries: string[] = []

  for (let i = 0; i < pluginFiles.length; i++) {
    const file = pluginFiles[i]
    const absPath = resolve(pluginsDir, file.filename)
    const varName = `plugin_${i}`
    const key = quoteKey(normalizePluginName(file.baseName) || 'unnamed')

    entries.push(`${key}: ${varName}`)
    importBlocks.push(`\
// ${file.filename}
let ${varName}
try {
  const mod_${i} = await import('${absPath}')
  ${varName} = mod_${i}.default
  if (!${varName} || typeof ${varName} !== 'object' || typeof ${varName}.setup !== 'function') {
    console.warn(\`[vike-plugins] File "${file.filename}" does not export a valid VikePlugin (expected default export from definePlugin()). Skipping.\`)
    ${varName} = null
  }
} catch (err) {
  console.warn(\`[vike-plugins] Failed to load plugin "${file.filename}":\`, err instanceof Error ? err.message : err)
  ${varName} = null
}
`)
  }

  return `\
// ============================================================
// virtual:vike-plugins
// ============================================================
//
// Auto-generated by vike-plugins.
// Plugins run only on the server (onCreatePageContext hook).
//
// ============================================================

${importBlocks.join('\n')}
export const rawPlugins = {
  ${entries.join(',\n  ')}
}
`
}
